# Generated by Django 4.1.13 on 2025-05-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachThue',
            fields=[
                ('KhachThueID', models.AutoField(primary_key=True, serialize=False)),
                ('HoVaTen', models.CharField(max_length=255)),
                ('NgaySinh', models.DateField(blank=True, null=True)),
                ('GioiTinh', models.CharField(blank=True, max_length=10, null=True)),
                ('SoDienThoai', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'KhachThue',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('VehicleTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'VehicleTypes',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('BienSoXe', models.CharField(max_length=50, unique=True)),
                ('HasMonthlyTicket', models.BooleanField(default=False)),
                ('KhachThueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_management.khachthue')),
                ('VehicleTypeID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking_management.vehicletypes')),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='PerTurnTicketRules',
            fields=[
                ('PerTurnRuleID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ShiftName', models.CharField(blank=True, max_length=100, null=True)),
                ('TimeFrom', models.TimeField(blank=True, null=True)),
                ('TimeTo', models.TimeField(blank=True, null=True)),
                ('VehicleTypeID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking_management.vehicletypes')),
            ],
            options={
                'db_table': 'PerTurnTicketRules',
            },
        ),
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('EntryTime', models.DateTimeField(auto_now_add=True)),
                ('ExitTime', models.DateTimeField(blank=True, null=True)),
                ('ProcessedLicensePlateEntry', models.CharField(blank=True, max_length=50, null=True)),
                ('ProcessedLicensePlateExit', models.CharField(blank=True, max_length=50, null=True)),
                ('EntryVehicleImagePath', models.CharField(blank=True, max_length=255, null=True)),
                ('EntryFaceImagePath', models.CharField(blank=True, max_length=255, null=True)),
                ('ExitVehicleImagePath', models.CharField(blank=True, max_length=255, null=True)),
                ('ExitFaceImagePath', models.CharField(blank=True, max_length=255, null=True)),
                ('CalculatedFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('WasMonthlyTicketUsed', models.BooleanField(default=False)),
                ('Status', models.CharField(blank=True, choices=[('IN_YARD', 'Đang trong bãi'), ('EXITED', 'Đã rời bãi')], max_length=50, null=True)),
                ('PerTurnRuleAppliedID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.perturnticketrules')),
                ('VehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.vehicle')),
            ],
            options={
                'db_table': 'ParkingHistory',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTicketRules',
            fields=[
                ('MonthlyRuleID', models.AutoField(primary_key=True, serialize=False)),
                ('PricePerMonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VehicleTypeID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking_management.vehicletypes')),
            ],
            options={
                'db_table': 'MonthlyTicketRules',
            },
        ),
    ]
