# Generated by Django 4.1.13 on 2025-05-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistory',
            name='EntryCroppedPlateImagePath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='ExitCroppedPlateImagePath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
