# Generated by Django 4.1.13 on 2025-06-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0002_parkinghistory_entrycroppedplateimagepath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistory',
            name='EntryOcrReadyImagePath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
