# Generated by Django 4.1.13 on 2025-06-05 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0003_parkinghistory_entryocrreadyimagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachthue',
            name='GioiTinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='khachthue',
            name='NgaySinh',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='khachthue',
            name='SoDienThoai',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có đúng 10 chữ số.', regex='^\\d{10}$')]),
        ),
    ]
