# Generated by Django 4.1.13 on 2025-06-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0004_alter_khachthue_gioitinh_alter_khachthue_ngaysinh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachthue',
            name='GioiTinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyticketrules',
            name='PricePerMonth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyticketrules',
            name='VehicleTypeID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking_management.vehicletypes'),
        ),
    ]
