# Generated by Django 4.1.13 on 2025-06-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0005_alter_khachthue_gioitinh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perturnticketrules',
            name='Price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
