# Generated by Django 4.1.13 on 2025-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0007_parkinghistory_vehicletypeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinghistory',
            name='EntryCroppedPlateImagePath',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='EntryFaceImagePath',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='EntryOcrReadyImagePath',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='ExitCroppedPlateImagePath',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='ExitFaceImagePath',
        ),
    ]
