# Generated by Django 4.1.13 on 2025-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0008_remove_parkinghistory_entrycroppedplateimagepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinghistory',
            name='PerTurnRuleAppliedID',
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='CalculatedFee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
