# Generated by Django 4.1.13 on 2025-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0010_ghinhanvethang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghinhanvethang',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Số tiền đã trả'),
        ),
    ]
