# Generated by Django 4.1.13 on 2025-06-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0011_alter_ghinhanvethang_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='HasMonthlyTicket',
        ),
    ]
