# Generated by Django 4.1.13 on 2025-06-19 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0012_remove_vehicle_hasmonthlyticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Xe', 'verbose_name_plural': 'Quản lý xe'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='NgayDangKy',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày đăng ký'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='BienSoXe',
            field=models.CharField(max_length=15, unique=True, verbose_name='Biển số xe'),
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
