# Generated by Django 4.1.13 on 2025-06-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0013_alter_vehicle_options_vehicle_ngaydangky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='NgayDangKy',
        ),
    ]
