# Generated by Django 4.1.13 on 2025-06-20 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0014_remove_vehicle_ngaydangky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachthue',
            name='SoDienThoai',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có đúng 10 chữ số.', regex='^\\d{10}$')]),
        ),
    ]
